[[chain]]
id = 'bip122:000000000019d6689c085ae165831e93'
name = 'Bitcoin'
aliases = ['BTC']

[[chain]]
id = 'eip155:1'
name = 'Ethereum'
aliases = ['ETH']

[[chain]]
id = 'xrpl:0'
name = 'XRP'
aliases = ['XRPL']

[[chain]]
id = 'eip155:56'
name = 'BSC'
aliases = ['BNB', 'Binance Chain']

[[chain]]
id = 'solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp'
name = 'Solana'
aliases = ['SOL']

[[chain]]
id = 'tron:0x2b6653dc'
name = 'TRON'
aliases = ['TRX']

[[chain]]
id = 'bip122:1a91e3dace36e2be3bf030a65679fe82'
name = 'Dogecoin'
aliases = ['DOGE']

[[chain]]
id = 'cardano:mainnet'
name = 'Cardano'
aliases = ['ADA']

[[chain]]
id = 'bip122:000000000000000000651ef99cb9fcbe'
name = 'Bitcoin Cash'
aliases = ['BCH']

[[chain]]
id = 'eip155:999'
name = 'Hyperliquid'
aliases = ['HYPE']

[[chain]]
id = 'canton:mainnet'
name = 'Canton'

[[chain]]
id = 'monero:418015bb9ae982a1975da7d79277c270'
name = 'Monero'
aliases = ['XMR']

[[chain]]
id = 'stellar:pubnet'
name = 'Stellar'
aliases = ['XLM']

[[chain]]
id = 'hedera:mainnet'
name = 'Hedera'

[[chain]]
id = 'bip122:12a765e31ffd4059bada1e25190f6e98'
name = 'Litecoin'
aliases = ['LTC']

[[chain]]
id = 'zcash:mainnet'
name = 'Zcash'

[[chain]]
id = 'eip155:43114'
name = 'Avalanche'
aliases = ['AVA']

[[chain]]
id = 'eip155:25'
name = 'Cronos'

[[chain]]
id = 'tvm:-239'
name = 'Toncoin'
aliases = ['TON', 'TVM']

[[chain]]
id = 'polkadot:91b171bb158e2d3848fa23a9f1c25182'
name = 'Polkadot'

[[chain]]
id = 'bittensor:mainnet'
name = 'Bittensor'

[[chain]]
id = 'pi:mainnet'
name = 'Pi'

[[chain]]
id = 'near:mainnet'
name = 'NEAR Protocol'

[[chain]]
id = 'eip155:61'
name = 'Ethereum Classic'

[[chain]]
id = 'icp:mainnet'
name = 'Internet Computer'

[[chain]]
id = 'eip155:137'
name = 'Polygon'

[[chain]]
id = 'cosmos:cosmoshub-4'
name = 'Cosmos'

[[chain]]
id = 'kaspa:mainnet'
name = 'Kaspa'

[[chain]]
id = 'algorand:wGHE2Pwdvd7S12BL5FaOP20EGYesN73k'
name = 'Algorand'

[[chain]]
id = 'fil:f'
name = 'Filecoin'

[[chain]]
id = 'aptos:1'
name = 'Aptos'

[[chain]]
id = 'eip155:50'
name = 'XDC Network'

[[chain]]
id = 'vechain:mainnet'
name = 'VeChain'

[[chain]]
id = 'decred:mainnet'
name = 'Decred'

[[chain]]
id = 'stacks:1'
name = 'Stacks'

[[chain]]
id = 'cosmos:pacific-1'
name = 'Sei'

[[chain]]
id = 'tezos:NetXdQprcVkpaWU'
name = 'Tezos'

[[chain]]
id = 'eip155:8217'
name = 'Kaia'

[[chain]]
id = 'eip155:8217'
name = 'Kaia'

[[chain]]
id = 'eip155:42161'
name = 'Arbitrum'
aliases = ['ARB']

[[chain]]
id = 'eip155:10'
name = 'Optimism'
aliases = ['OP']

[[chain]]
id = 'eip155:8453'
name = 'Base'

[[chain]]
id = 'sui:mainnet'
name = 'Sui'
aliases = ['SUI']

[[chain]]
id = 'cosmos:injective-1'
name = 'Injective'
aliases = ['INJ']

[[chain]]
id = 'cosmos:osmosis-1'
name = 'Osmosis'
aliases = ['OSMO']

[[chain]]
id = 'cosmos:celestia'
name = 'Celestia'
aliases = ['TIA']

[[chain]]
id = 'starknet:SN_MAIN'
name = 'Starknet'

[[chain]]
id = 'eip155:169'
name = 'Manta Pacific'
aliases = ['MANTA']

[[chain]]
id = 'eip155:324'
name = 'zkSync Era'
aliases = ['ZKSERA']

[[chain]]
id = 'eip155:59144'
name = 'Linea'
aliases = ['LINEAETH']

[[chain]]
id = 'eip155:146'
name = 'Sonic'

[[chain]]
id = 'eip155:80084'
name = 'Berachain'
aliases = ['BERA']

[[chain]]
id = 'eip155:1111'
name = 'WEMIX'

[[chain]]
id = 'eip155:42220'
name = 'Celo'

[[chain]]
id = 'waves:087'
name = 'Waves'

[[chain]]
id = 'bip122:00000ffd590b1485b3ca31f031121ecb'
name = 'Dash'
aliases = ['DASH']

[[chain]]
id = 'eip155:361'
name = 'Theta'

[[chain]]
id = 'multiversx:1'
name = 'MultiversX'
aliases = ['EGLD']

[[chain]]
id = 'cosmos:akashnet-2'
name = 'Akash'
aliases = ['AKT']

[[chain]]
id = 'eip155:32770'
name = 'Zilliqa'
aliases = ['ZIL']

[[chain]]
id = 'eip155:32769'
name = 'Zilliqa 2'
aliases = ['ZIL']

[[chain]]
id = 'bip122:000000000019d6689c085ae165831e93'
name = 'Verge'
aliases = ['XVG']

[[chain]]
id = 'cosmos:bandchain-1'
name = 'Band Protocol'
aliases = ['BAND']

[[chain]]
id = 'klever:mainnet'
name = 'Klever'
aliases = ['KLV']

[[chain]]
id = 'cosmos:coreum-mainnet-1'
name = 'Coreum'

[[chain]]
id = 'eip155:58'
name = 'Ontology'
aliases = ['ONT', 'ONG']

[[chain]]
id = 'nano:mainnet'
name = 'Nano'

[[chain]]
id = 'cosmos:fetchhub-4'
name = 'Fetch.ai'
aliases = ['FET']

[[chain]]
id = 'bip122:0000041e3d64c06cf591ed5f865910'
name = 'PIVX'

[[chain]]
id = 'bip122:1a91e3dace36e2be3bf030a65679fe'
name = 'DigiByte'
aliases = ['DGB']

[[chain]]
id = 'icon:1'
name = 'ICON'
aliases = ['ICX']

[[chain]]
id = 'casper:casper'
name = 'Casper'
aliases = ['CSPR']

[[chain]]
id = 'eip155:14'
name = 'Flare'
aliases = ['FLR']
